/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f411xx.h"
#include "stm32f411xx_GPIO_driver.h"
#include "stm32f411xx_SPI_driver.h"
//#include "stm32f411xx_GPIO_driver.h"

int8_t btn_status = 1;

void delay(void) {
	for (uint32_t i =0; i < 500000; i++) {

	}
}

int main(void)
{
	GPIO_Handle_t GPIO_LED, GPIO_BTN;
	memset(&GPIO_LED, 0, sizeof(GPIO_LED));
	memset(&GPIO_BTN, 0, sizeof(GPIO_BTN));

	GPIO_LED.pGPIO = GPIOC;
	GPIO_LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_LED.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_PIN_PU;		/* pull-up*/
	GPIO_LED.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
//	GPIO_LED.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_SPEED_FAST;
	GPIO_PeriClockCtrl(GPIO_LED.pGPIO, ENABLE);
	GPIO_Init(&GPIO_LED);

	GPIO_BTN.pGPIO = GPIOA;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_PIN_PU;		/* pull-up*/
	GPIO_BTN.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;

	GPIO_PeriClockCtrl(GPIO_BTN.pGPIO, ENABLE);
	GPIO_Init(&GPIO_BTN);
	/*interrupt configure*/
	GPIO_IRQ_ISR_Config(IRQ_NO_EXTI0, ENABLE);
	GPIO_IRQ_PRIO_Config(IRQ_NO_EXTI0, IRQ_PRIO_3);
    /* Loop forever */
//	for(;;);
//	uint8_t btn_status = 1;
	while(1) {
		GPIO_TogglePin(GPIO_LED.pGPIO, GPIO_LED.GPIO_PinConfig.GPIO_PinNumber);
		if ( !GPIO_ReadInputPin(GPIO_BTN.pGPIO, GPIO_PIN_NO_0) ) {
			/*press down*/
			delay();
			btn_status = -btn_status;

		}

		if ( btn_status == 1 ) {
			GPIO_WriteOutputPin(GPIO_LED.pGPIO, GPIO_PIN_NO_13, GPIO_PIN_SET);
		} else {
			GPIO_WriteOutputPin(GPIO_LED.pGPIO, GPIO_PIN_NO_13, GPIO_PIN_RESET);
		}
//		delay();
	}
}

void EXTI0_IRQHandler(void) {
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	btn_status = -btn_status;
}
