/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f411xx.h"
#include "stm32f411xx_GPIO_driver.h"
#include "stm32f411xx_SPI_driver.h"

#include "spi.h"
//#include "stm32f411xx_GPIO_driver.h"

int8_t btn_status = 1;

uint8_t tx_buffer[3] = {1, 2, 3};
uint8_t rx_buffer[3];

void delay(void) {
	for (uint32_t i =0; i < 500000; i++) {

	}
}

int main(void)
{
	GPIO_Handle_t GPIO_LED, GPIO_BTN;
	memset(&GPIO_LED, 0, sizeof(GPIO_LED));
	memset(&GPIO_BTN, 0, sizeof(GPIO_BTN));

	GPIO_LED.pGPIO = GPIOC;
	GPIO_LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_LED.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_PIN_PU;		/* pull-up*/
	GPIO_LED.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
//	GPIO_LED.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_SPEED_FAST;
//	GPIO_PeriClockCtrl(GPIO_LED.pGPIO, ENABLE);
	GPIO_Init(&GPIO_LED);

	GPIO_BTN.pGPIO = GPIOA;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_BTN.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_PIN_PU;		/* pull-up*/
//	GPIO_BTN.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;

//	GPIO_PeriClockCtrl(GPIO_BTN.pGPIO, ENABLE);
	GPIO_Init(&GPIO_BTN);
	/*interrupt configure*/
	GPIO_IRQ_PRIO_Config(IRQ_NO_EXTI0, IRQ_PRIO_3);
	GPIO_IRQ_ISR_Config(IRQ_NO_EXTI0, ENABLE);

//	SPI1_Init();
//	SPI2_Init();

	/*
	 * SPI1_SS		-	A4
	 * SPI1_CLK 	- 	A5
	 * SPI1_MISO 	-	A6
	 * SPI1_MOSI	-	A7
	 */
	/* 1. Configure GPIO for SPI1 */
	GPIO_Handle_t GPIO_SPI1;
	memset(&GPIO_SPI1, 0, sizeof(GPIO_SPI1));

	GPIO_SPI1.pGPIO = GPIOA;
//	GPIO_SPI1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
//	GPIO_SPI1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
//	GPIO_SPI1.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_NO_PU_PD;
//	GPIO_SPI1.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
//	GPIO_SPI1.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_ALTFUNC_5;



	/* SPI1_CLK */
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_NO_PU_PD;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_ALTFUNC_5;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GPIO_Init(&GPIO_SPI1);

	/* SPI1_MISO */
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_NO_PU_PD;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_ALTFUNC_5;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	GPIO_Init(&GPIO_SPI1);

	/* SPI1_MOSI */
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_NO_PU_PD;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_ALTFUNC_5;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
	GPIO_Init(&GPIO_SPI1);

	/* SPI1_SS */
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_PIN_PD;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
	GPIO_SPI1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_4;
	GPIO_Init(&GPIO_SPI1);

	/* 2. Configure SPI1 properties */
	SPI_Handle_t SPI1_Handle;
	memset(&SPI1_Handle, 0, sizeof(SPI1_Handle));

	SPI1_Handle.SPIx = SPI1;
	SPI1_Handle.SPIConfig.SPI_DeviceMode = SPI_MODE_MASTER;
	SPI1_Handle.SPIConfig.SPI_BusConfig = SPI_BUS_HDUPLEX;
	SPI1_Handle.SPIConfig.SPI_ClkSpeed = SPI_CLOCK_SPEED_DIV_8;
	SPI1_Handle.SPIConfig.SPI_DFF = SPI_DATA_FRAME_8;
	SPI1_Handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI1_Handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI1_Handle.SPIConfig.SPI_SSM = SPI_SSM_EN;

	SPI_Init(&SPI1_Handle);
	SPI_PeripheralControl(SPI1_Handle.SPIx, ENABLE);

	/*
	 * SPI2_SS		-	B9
	 * SPI2_CLK		-	B10
	 * SPI2_MISO	-	B14
	 * SPI2_MOSI	-	B15
	 */

	/* 1. Configure GPIO for SPI1 */
	GPIO_Handle_t GPIO_SPI2;
	memset(&GPIO_SPI2, 0, sizeof(GPIO_SPI2));

	GPIO_SPI2.pGPIO = GPIOB;
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_NO_PU_PD;
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinOutputType = GPIO_OUT_PUSHPULL;
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinAltFuncMode = GPIO_ALTFUNC_5;

	/* SPI2_SS */
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
	GPIO_Init(&GPIO_SPI2);

	/* SPI2_CLK */
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_10;
	GPIO_Init(&GPIO_SPI2);

	/* SPI2_MISO */
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GPIO_Init(&GPIO_SPI2);

	/* SPI2_MOSI */
	GPIO_SPI2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&GPIO_SPI2);

	/* 2. Configure SPI1 properties */
	SPI_Handle_t SPI2_Handle;
	memset(&SPI2_Handle, 0, sizeof(SPI2_Handle));

	SPI2_Handle.SPIx = SPI2;
	SPI2_Handle.SPIConfig.SPI_DeviceMode = SPI_MODE_SLAVE;
	SPI2_Handle.SPIConfig.SPI_BusConfig = SPI_BUS_FDUPLEX;
	SPI2_Handle.SPIConfig.SPI_ClkSpeed = SPI_CLOCK_SPEED_DIV_8;
	SPI2_Handle.SPIConfig.SPI_DFF = SPI_DATA_FRAME_8;
	SPI2_Handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI2_Handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI2_Handle.SPIConfig.SPI_SSM = SPI_SSM_DIS;

	SPI_Init(&SPI2_Handle);
	SPI_PeripheralControl(SPI2_Handle.SPIx, ENABLE);


	GPIO_WriteOutputPin(GPIO_SPI1.pGPIO, GPIO_PIN_NO_4, GPIO_PIN_RESET);
    /* Loop forever */
//	for(;;);
//	uint8_t btn_status = 1;
	while(1) {
//		GPIO_TogglePin(GPIO_LED.pGPIO, GPIO_LED.GPIO_PinConfig.GPIO_PinNumber);
//		if ( !GPIO_ReadInputPin(GPIO_BTN.pGPIO, GPIO_PIN_NO_0) ) {
//			/*press down*/
//			delay();
//			btn_status = -btn_status;
//
//		}
//		GPIO_WriteOutputPin(GPIO_SPI1.pGPIO, GPIO_PIN_NO_4, GPIO_PIN_SET);
		if ( btn_status == -1 ) {
			delay();
			GPIO_WriteOutputPin(GPIO_LED.pGPIO, GPIO_PIN_NO_13, GPIO_PIN_RESET);

			GPIO_WriteOutputPin(GPIO_SPI1.pGPIO, GPIO_PIN_NO_4, GPIO_PIN_RESET);
			SPI_Transmit(SPI1, tx_buffer, 1);

//			SPI_Receive(SPI2, rx_buffer, 1);
			GPIO_WriteOutputPin(GPIO_SPI1.pGPIO, GPIO_PIN_NO_4, GPIO_PIN_SET);
			btn_status=1;
		} else {
			GPIO_WriteOutputPin(GPIO_LED.pGPIO, GPIO_PIN_NO_13, GPIO_PIN_SET);
			delay();
		}
//		delay();
	}
}

void EXTI0_IRQHandler(void) {
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	btn_status = -1;
}
